### ISSUE TITLE
Code Suggestion

### ISSUE THREAD

**Issue by reinacchi** [darccyy/mousr#1]
**Is your feature request related to a problem? Please describe.**
Continuous topics from https://github.com/darccyy/mousr-old/issues/2

**Describe the solution you'd like**
I found a similar old repository https://github.com/4strid/mouse-control.autohotkey which has better cursor movement. I'm wondering if you could get the logic implemented the same way but better (key customisation).

**Describe alternatives you've considered**
- ~~The repository I mentioned above has a mode that intercepts keys to control the mouse and another to act like a regular keyboard (all keys disabled). I figured it'll be a good idea to have this implemented as well~~ Nevermind! I completely forgot `Alt+Insert` exists.

I'm not an expert in AutoHotKey and am unable to open a PR but the best I can do is open an issue. Thanks again :)

**Comment by dxrcy** [comment]
Thanks for the suggestion! [Version 1.1.0](https://github.com/darccyy/mousr/releases/tag/v1.1.0) has been released and *might* fix the mouse movement. I'm not too sure what is causing the stiffness... 👍

**Comment by reinacchi** [comment]
Thanks for the update! Unfortunately, the stiffness of the mouse _still_ occurring.

https://user-images.githubusercontent.com/73813638/182976372-b1d1384a-1b12-4285-9ffd-5f51377e833f.mp4

Here's a video of how https://github.com/4strid/mouse-control.autohotkey works mouse movement works. I think you can search around in the repo's code and have them implemented.

**Comment by dxrcy** [comment]
Do you think that acceleration and deceleration are better that static speed? If so that should be pretty easy to add 👍

**Comment by reinacchi** [comment]
Yeah, they seem better to me.
